local bind_all = require("conf.bindings").bind_all
local key_opts = { silent = true }

bind_all("base.write", ":w<CR>", {}, key_opts)
bind_all("base.toggle_line_numbers", ":set nu!<CR>", {}, key_opts)
bind_all("base.open_bottom_panel", ":botright 20split<CR>", {}, key_opts)
bind_all("base.open_new_vsplit", ":vnew<CR>", {}, key_opts)
bind_all("base.win_fix_width", ":set wfw<CR>", {}, key_opts)
bind_all("base.win_fix_height", ":set wfh<CR>", {}, key_opts)
bind_all("base.quickfix_next", ":cnext<CR>", {}, key_opts)
bind_all("base.quickfix_prev", ":cprev<CR>", {}, key_opts)
bind_all("base.loclist_next", ":lnext<CR>", {}, key_opts)
bind_all("base.loclist_prev", ":lprev<CR>", {}, key_opts)
bind_all("base.tab_next", ":tabnext<CR>", {}, key_opts)
bind_all("base.tab_prev", ":tabprev<CR>", {}, key_opts)
bind_all("base.tab_add", ":tabnew<CR>", {}, key_opts)
bind_all("base.tab_close", ":tabclose<CR>", {}, key_opts)
bind_all("base.buf_next", ":bnext<CR>", {}, key_opts)
bind_all("base.buf_prev", ":bprevious<CR>", {}, key_opts)

bind_all("colorscheme.next", function()
  require("conf.util.theme_cycler")()
end, {}, {})

bind_all("diag.show_line", vim.diagnostic.open_float, {}, key_opts)
bind_all("diag.prev", vim.diagnostic.goto_prev, {}, key_opts)
bind_all("diag.next", vim.diagnostic.goto_next, {}, key_opts)
bind_all("diag.set_loclist", vim.diagnostic.setloclist, {}, key_opts)

bind_all("fs.file_path", function()
  local yank = require("conf.util.yank")
  local fs = require("conf.util.fs")
  yank(fs.file_path())
end, {}, {})
bind_all("fs.file_path_abs", function()
  local yank = require("conf.util.yank")
  local fs = require("conf.util.fs")
  yank(fs.file_path_abs())
end, {}, {})
